server:
  port: 9999

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
   user :
    path: /user/**
    serviceId: user-service



